Return warnings in the filtered response
n1ru4l/graphql-public-schema-filter pull request #170
Opened 2022-11-14 15:07 UTC by joseph-neeraj

2022-11-14 15:11 UTC, joseph-neeraj commented
@n1ru4l Please check this. I'm also unsure of the versioning, though I'd think it's okay to publish it as a minor version upgrade because the lib is still in alpha in npm.

2022-11-16 17:09 UTC, joseph-neeraj commented
@n1ru4l any feedback is welcome. Thanks.

2022-11-16 17:16 UTC, n1ru4l commented
Hey @joseph-neeraj, thank you for your contribution!

After thinking about this a bit, it might be a better solution to instead allow providing your own `onWarning` function, that allows generating the warning error array in userland.

https://github.com/n1ru4l/graphql-public-schema-filter/blob/c2be0c56208f516e3d5833689a1781ed159145e4/src/public-schema-filter.ts#L70-L72

```ts
const warnings = []
const onWarning = (warning) => warning.push(warning)
buildPublicSchema({ schema, onWarning })
```

2022-11-21 10:10 UTC, n1ru4l requested changes
hey @joseph-neeraj , can you please apply the feedback? Would love to get this one merged an released!

2022-11-21 10:20 UTC, joseph-neeraj commented
will do @n1ru4l , been busy, I'll update it as soon as I get a chance, thanks :)

2022-11-21 18:52 UTC, joseph-neeraj commented
Superseded by this [alternative MR](https://github.com/n1ru4l/graphql-public-schema-filter/pull/171).

2022-11-21 18:52 UTC, closed without merging